<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMx7wxNU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMx7wxNU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMx7wxNU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMx7wxNU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMx7wxNU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Mx7wxNU',
    'container.build_id' => '50c6947e',
    'container.build_time' => 1555330074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMx7wxNU');
