<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0zYZYeK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0zYZYeK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0zYZYeK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0zYZYeK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0zYZYeK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0zYZYeK',
    'container.build_id' => '168dd29d',
    'container.build_time' => 1552485498,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0zYZYeK');
