<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWu0kEv3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWu0kEv3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWu0kEv3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWu0kEv3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWu0kEv3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Wu0kEv3',
    'container.build_id' => 'a924ceb3',
    'container.build_time' => 1550052994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWu0kEv3');
